### PR TITLE
Boilerplate: Update to 25bf1477435cc1d54ed1a0dff1c1f16405144db3

### PR DESCRIPTION
**Pull request by 2uasimojo**
Conventions:
- openshift/golang-osd-operator: Update
---
https://github.com/openshift/boilerplate/compare/1813fd0bf548ea39983ed6ed7ed7adab924ab5bf...25bf1477435cc1d54ed1a0dff1c1f16405144db3

commit: 567b9545e8fbdc825306c7d8a4ec1bfe2c893236
author: Eric Fried
openshift/golang-osd-operator: openapi-gen

Make consumers produce openapi by adding a target called
`openapi-generate` which runs `openapi-gen` if necessary. Put it in the
chain for `generate`.

commit: a0f4fba9914a5d95a5605f59e5fb87759917f3c8
author: Eric Fried
Image: Fix tests for image-v0.4.0

commit: 7bcdbc25c7614d5053a5bcef337bd4fbcb9f23a7
author: Eric Fried
Image: Install mockgen and openapi-gen

These will be used by `go-generate` and `op-generate`, respectively.

commit: c1b444f2f0fafc06afdee1f87629096e7185d11a
author: Eric Fried
Image: Don't use gvm

It turns out we don't need go1.14, so we don't need gvm. If we need to
upgrade the version of go used by consumers, we'll instead update the
backing image.

This (mostly) reverts commit 5efde524a0104b8b076f721144469934ac033391.

commit: e654a8ad5d75e0da63888b5be944ad605de2b226
author: Eric Fried
Update subscribers

...and fix a buglet introduced by 4feb777c that breaks on downlevel or
not-yet-onboarded consumers.

commit: 8159de6a4550f652c1033097f5b89a819cc11dd6
author: Eric Fried
pr-check: Color test output

...so it can be visually distinguished from the output of the commands
run by the tests. This will make debugging easier.

commit: ed5706ecedc236099532a0edb2c5a37e41e0235f
author: Rafa Porres Molina
Fix unbound variable

Older versions of bash didn't like it

Signed-off-by: Rafa Porres Molina <rporresm@redhat.com>

commit: 4e834ca28bce6dc24b65f141d03cccc12ce8b256
author: Rafa Porres Molina
Fix non-existing target

Signed-off-by: Rafa Porres Molina <rporresm@redhat.com>

commit: 596add63d56be4cd085ddb1606bc8c4c47883aee
author: Rafa Porres Molina
Add opm-build-push target

* Opt-in target, we are not ready to force anyone to use this
* Adds a script to build catalog using opm
* Adds authentication to docker-push (breaking change)
* Depends on a local hack/generate-bundle-contents.py script

Signed-off-by: Rafa Porres Molina <rporresm@redhat.com>

commit: 46751efaeb58fa435659ee80a0787119ca3d8d4b
author: Eric Fried
Make go-build only build

Since we're running them in prow, and have made sure the prow
environment matches the appsre environment, there's no need for
validation steps like linting and `go test` to be run as part of the
container build.

This commit makes `make go-build` only do the go build. Since `make
go-build` is the crux of `make docker-build`, this makes the container
build more efficient.

(Note that, prior to #103, `make docker-build` was the only way to run
these validation pieces "locally" in the proper container. Now you can
do it with `boilerplate/_lib/container-make {target}`.)

commit: 4feb777cb9d58159ea6d1c3e5f83fa7ac2cf294a
author: Eric Fried
Support containerized local builds

Add a utility, boilerplate/_lib/container-make, which can be used as a
drop-in replacement for the real `make` to invoke the target(s) in the
boilerplate container appropriate to the current level of boilerplate.

[OSD-5096](https://issues.redhat.com/browse/OSD-5096)

### CODE REVIEW

**Review by 2uasimojo — COMMENTED** [review]
/hold

Needs a fixup commit.

**Review by 2uasimojo — COMMENTED** [review]
/retest

Get real results now that the boilerplate backing image is [properly mirrored](https://github.com/openshift/release/pull/14879)

**Comment by 2uasimojo** [comment]
/hold cancel

Followup commit in place.

**Comment by lisa** [comment]
/lgtm
/approve

👍 for dual commits to encapsulate what changed for boilerplate itself and the in-repo changes here.

**Pull request merged**
