### PR TITLE
OSD-11019 update boilerplate to v2.2.0

### PR DESCRIPTION
**Pull request by rendhalver**
[OSD-11019](https://issues.redhat.com//browse/OSD-11019) update boilerplate to version v2.2.0

### CODE REVIEW

**Comment by ravitri** [comment]
@rendhalver - Could you please also add a description to the PR? Details like purpose of this PR and tracking tickets will help to understand context of the change.

**Comment by rendhalver** [comment]
> @rendhalver - Could you please also add a description to the PR? Details like purpose of this PR and tracking tickets will help to understand context of the change.

Should I have used the `make boilerplate-commit` command instead of creating this commit manually?

**Comment by rendhalver** [comment]
I have tested this in a staging cluster and it looks to be behaving as expected.
I created a new `SubjectPermission` resource and it created the resources as expected.

**Comment by mrbarge** [comment]
/approve

> > @rendhalver - Could you please also add a description to the PR? Details like purpose of this PR and tracking tickets will help to understand context of the change.
> 
> Should I have used the `make boilerplate-commit` command instead of creating this commit manually?

The commit itself is fine but mentioning the associated Jira ticket in the PR description will cause an automatic link to be added to the Jira ticket to reference this PR which is quite helpful for tracking.

We should add a PR template to this repo which will help prompt those inputs. Would you mind having a look at that @rendhalver ?  Our MUO one [is here](https://github.com/openshift/managed-upgrade-operator/blob/master/.github/PULL_REQUEST_TEMPLATE.md) as an example.

**Comment by rendhalver** [comment]
/wip

> /approve
> 
> > > @rendhalver - Could you please also add a description to the PR? Details like purpose of this PR and tracking tickets will help to understand context of the change.
> > 
> > 
> > Should I have used the `make boilerplate-commit` command instead of creating this commit manually?
> 
> The commit itself is fine but mentioning the associated Jira ticket in the PR description will cause an automatic link to be added to the Jira ticket to reference this PR which is quite helpful for tracking.
> 
> We should add a PR template to this repo which will help prompt those inputs. Would you mind having a look at that @rendhalver ? Our MUO one [is here](https://github.com/openshift/managed-upgrade-operator/blob/master/.github/PULL_REQUEST_TEMPLATE.md) as an example.



> /approve
> 
> > > @rendhalver - Could you please also add a description to the PR? Details like purpose of this PR and tracking tickets will help to understand context of the change.
> > 
> > 
> > Should I have used the `make boilerplate-commit` command instead of creating this commit manually?
> 
> The commit itself is fine but mentioning the associated Jira ticket in the PR description will cause an automatic link to be added to the Jira ticket to reference this PR which is quite helpful for tracking.

Ahha I had missed that. I updated the description to include that.

> 
> We should add a PR template to this repo which will help prompt those inputs. Would you mind having a look at that @rendhalver ? Our MUO one [is here](https://github.com/openshift/managed-upgrade-operator/blob/master/.github/PULL_REQUEST_TEMPLATE.md) as an example.
Sounds good I will open a PR to get that added.

**Pull request merged**
