### PR TITLE
osde2e test decentralization

### PR DESCRIPTION
**Pull request by jbpratt**
- Boilerplate: Update to d3612328c972f49103b8fd1be49cd8b0a387c980
- osde2e: initial commit

### What type of PR is this?
_(bug/feature/cleanup/documentation/test/refactor)_

### Which Jira/Github issue(s) this PR fixes?

[SDCICD-1022](https://issues.redhat.com//browse/SDCICD-1022)

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR

### CODE REVIEW

**Comment by jbpratt** [comment]
depends on https://github.com/openshift/osde2e-common/pull/3

**Comment by mrbarge** [comment]
@jbpratt could you confirm if the test-harness quay repo is needed prior to this merging, or will that be enabled separately in app-interface?

**Comment by jbpratt** [comment]
> @jbpratt could you confirm if the test-harness quay repo is needed prior to this merging, or will that be enabled separately in app-interface?

hey @mrbarge, the quay repo isn't needed until we open the MR to update the build command in app-interface. At that point, the image will be pushed (or attempted to). Thanks for confirming!

**Comment by mrbarge** [comment]
Awesome, cheers!
/lgtm
/approve

**Comment by ryankwilliams** [comment]
For SDCICD-1036

**Pull request merged**
