### PR TITLE
Boilerplate update + updates for using boilerplate CSV/bundle handling

### PR DESCRIPTION
**Pull request by bdematte**
In addition of onboarding the latest version of boilerplate, this MR contains the needed changes to adapt to boilerplate management of the CSV and the bundle.

Changes for the bundle : 
- Resource which were not embedded in the bundle have been moved to `examples/other_resources` and examples to `examples`

Testing
catalog image
```
% docker run --name catalog-image -d --rm --network host "quay.io/$IMAGE_REPOSITORY/rbac-permissions-operator-registry:staging-latest" 
3066bc059e65d730858b7525944037fdc016fef69cf55a075cc2991807248153
% docker run --rm --network=host quay.io/rogbas/grpcurl -plaintext localhost:50051 api.Registry/ListBundles | jq '.version' | grep 156 
"0.1.156-aef458a"
```

CSV
```
% diff saas-rbac-permissions-operator-bundle/rbac-permissions-operator/0.1.156-aef458a/rbac-permissions-operator.v0.1.156-aef458a.clusterserviceversion.yaml saas-rbac-permissions-operator-bundle/rbac-permissions-operator/0.1.154-3816760/rbac-permissions-operator.v0.1.154-3816760.clusterserviceversion.yaml 
8c8
<     createdAt: '2021-04-14T17:39:17Z'
---
>     createdAt: '2021-04-07T13:30:57Z'
11c11
<   name: rbac-permissions-operator.v0.1.156-aef458a
---
>   name: rbac-permissions-operator.v0.1.154-3816760
73c73
<                 image: quay.io/bdematte/rbac-permissions-operator@sha256:a59f7f710b4c09bee0a650c0c6328dfba5c5eb0f00209a7c6a1b3229849c5829
---
>                 image: quay.io/app-sre/rbac-permissions-operator:3816760
100,101c100,101
<   replaces: rbac-permissions-operator.v0.1.154-3816760
<   version: 0.1.156-aef458a
---
>   replaces: rbac-permissions-operator.v0.1.152-f0cfa43
>   version: 0.1.154-3816760
```

### CODE REVIEW

**Comment by 2uasimojo** [comment]
/hold

for py3 fix

**Comment by 2uasimojo** [comment]
Yup, other than needing the py3 fix, this lgtm.

**Comment by bdematte** [comment]
Latest commit contains the fix for py3 (validated with osd-metric-exporter)

**Comment by 2uasimojo** [comment]
> Latest commit contains the fix for py3 (validated with osd-metric-exporter)

Yes it does.

/lgtm
/hold cancel

**Comment by 2uasimojo** [comment]
/hold

One more fix needed here

**Comment by 2uasimojo** [comment]
Keep the hold so we can control when this lands. Thanks!

**Comment by 2uasimojo** [comment]
Landing this now

/hold cancel

**Pull request merged**
