### PR TITLE
OSD-7601

### PR DESCRIPTION
**Pull request by robotmaxtron**
Boilerplate + op-generate to v1

### CODE REVIEW

**Comment by robotmaxtron** [comment]
I can squash the two commits prior to merging, separated for clarity.

**Comment by 2uasimojo** [comment]
Boilerplate update is legit.

I installed the new CRD and it validates. `oc explain` now works too.

> I can squash the two commits prior to merging, separated for clarity.

Personally I prefer them to remain separate. But hey, not my repo :P

**Review by fahlmant — APPROVED** [review]
/lgtm

**Comment by 2uasimojo** [comment]
/lgtm

bp update should make this work now.

**Pull request merged**
