### PR TITLE
[OSD-10257] update operator-sdk and dependencies version

### PR DESCRIPTION
**Pull request by bmeng**
update the dependency version

operator-sdk 0.18.2
controller-runtime 0.10.0
kube-* 0.22.1

### CODE REVIEW

**Comment by mrbarge** [comment]
We haven't normally included the vendor dir for this project, was its inclusion as part of this PR an accident?

**Comment by ravitri** [comment]
/hold
Adding a hold till the query on vendoring deps is addressed

**Comment by bmeng** [comment]
Tested with some self created `SubjectPermission`, did not see errors in the operator log, and the corresponding rolebindings created in the target namespace.

**Comment by ravitri** [comment]
Tested it locally as well and all seems fine. Adding lgtm for now to let it pass through e2e tests over weekend to capture issues if any. 

/lgtm
/approve

**Pull request merged**
